import type { Business, DayHours } from "../types";

function week(open: string, close: string, closedDays: number[] = []): DayHours[] {
  return ([0, 1, 2, 3, 4, 5, 6] as const).map((day) => ({
    day,
    open,
    close,
    closed: closedDays.includes(day),
  }));
}

/**
 * Seed businesses around south-east Bengaluru.
 * Distinct from production data — swap for Supabase reads in Milestone 6.
 */
export const BUSINESSES: Business[] = [
  {
    id: "biz_corner_copy",
    slug: "corner-copy-and-more",
    name: "Corner Copy & More",
    categoryId: "print-documents",
    categoryLabel: "Print & Documents",
    description:
      "A neighbourhood print shop that still answers the phone. Documents, copies, and last-minute spiral binds.",
    tags: ["Colour print", "B&W", "Binding", "Scanning"],
    rating: 4.7,
    reviewCount: 214,
    location: { lat: 12.9364, lng: 77.6229 },
    neighborhood: "Koramangala 5th Block",
    address: "14, 5th Cross, Koramangala, Bengaluru",
    hours: week("08:30", "21:00"),
    typicalResponseMinutes: 8,
    monogram: "CC",
    mark: "fill",
  },
  {
    id: "biz_circuit_bench",
    slug: "circuit-bench",
    name: "Circuit Bench",
    categoryId: "repairs",
    categoryLabel: "Repairs",
    description:
      "Phone and laptop repairs without the mall-counter wait. Most screen jobs are done the same afternoon.",
    tags: ["Mobiles", "Laptops", "Screens"],
    rating: 4.6,
    reviewCount: 189,
    location: { lat: 12.9379, lng: 77.6258 },
    neighborhood: "Koramangala 6th Block",
    address: "218, 80 Feet Road, Koramangala, Bengaluru",
    hours: week("10:00", "20:00", [0]),
    typicalResponseMinutes: 12,
    monogram: "CB",
    mark: "soft",
  },
  {
    id: "biz_hemline",
    slug: "hemline",
    name: "Hemline",
    categoryId: "tailoring",
    categoryLabel: "Tailoring",
    description:
      "Walk-in tailoring for everyday clothes. Hems, fits, and the odd emergency button.",
    tags: ["Alterations", "Stitching", "Uniforms"],
    rating: 4.8,
    reviewCount: 96,
    location: { lat: 12.9321, lng: 77.6214 },
    neighborhood: "Koramangala 4th Block",
    address: "7, 4th Main, Koramangala, Bengaluru",
    hours: week("10:30", "19:30", [3]),
    typicalResponseMinutes: 45,
    monogram: "HE",
    mark: "line",
  },
  {
    id: "biz_studio_24",
    slug: "studio-24",
    name: "Studio 24",
    categoryId: "photography",
    categoryLabel: "Photography",
    description:
      "Passport photos, portraits, and a quiet back room for documents that need to look official.",
    tags: ["Passport photos", "Portraits"],
    rating: 4.5,
    reviewCount: 151,
    location: { lat: 12.9392, lng: 77.6296 },
    neighborhood: "Koramangala 7th Block",
    address: "24, Industrial Layout, Koramangala, Bengaluru",
    hours: week("09:00", "20:00"),
    typicalResponseMinutes: 20,
    monogram: "S2",
    mark: "fill",
  },
  {
    id: "biz_paper_drawer",
    slug: "the-paper-drawer",
    name: "The Paper Drawer",
    categoryId: "stationery",
    categoryLabel: "Stationery",
    description: "Notebooks, pens, files, and the stationery you always mean to restock.",
    tags: ["Notebooks", "Files", "Art supplies"],
    rating: 4.4,
    reviewCount: 73,
    location: { lat: 12.934, lng: 77.6188 },
    neighborhood: "Koramangala 4th Block",
    address: "32, 8th Main, Koramangala, Bengaluru",
    hours: week("10:00", "20:30", [0]),
    typicalResponseMinutes: 55,
    monogram: "PD",
    mark: "soft",
  },
  {
    id: "biz_househands",
    slug: "househands",
    name: "HouseHands",
    categoryId: "home-services",
    categoryLabel: "Home Services",
    description:
      "Electricians, plumbers, and the person who can look at that loose ceiling fan this week.",
    tags: ["Electrical", "Plumbing", "Assembly"],
    rating: 4.3,
    reviewCount: 128,
    location: { lat: 12.9288, lng: 77.6304 },
    neighborhood: "Jakkasandra",
    address: "11, 1st Cross, Jakkasandra, Bengaluru",
    hours: week("08:00", "19:00", [0]),
    typicalResponseMinutes: 25,
    monogram: "HH",
    mark: "line",
  },
  {
    id: "biz_forge_form",
    slug: "forge-and-form",
    name: "Forge & Form",
    categoryId: "custom-work",
    categoryLabel: "Custom Work",
    description:
      "Small-run fabrication. Nameplates, frames, and custom pieces that shouldn’t need a factory.",
    tags: ["Nameplates", "Frames", "Acrylic"],
    rating: 4.9,
    reviewCount: 41,
    location: { lat: 12.9411, lng: 77.6231 },
    neighborhood: "Koramangala 6th Block",
    address: "9, 3rd Cross, Koramangala, Bengaluru",
    hours: week("11:00", "19:00", [0, 1]),
    typicalResponseMinutes: 120,
    monogram: "FF",
    mark: "fill",
  },
  {
    id: "biz_bindwell",
    slug: "bindwell-press",
    name: "Bindwell Press",
    categoryId: "print-documents",
    categoryLabel: "Print & Documents",
    description:
      "Spiral, thermal, and hard-cover binding. Thesis season is their busy season — message before you visit.",
    tags: ["Binding", "Lamination", "Thesis"],
    rating: 4.6,
    reviewCount: 88,
    location: { lat: 12.9332, lng: 77.6274 },
    neighborhood: "Koramangala 8th Block",
    address: "41, 80 Feet Road, Koramangala, Bengaluru",
    hours: week("09:00", "20:00", [0]),
    typicalResponseMinutes: 18,
    monogram: "BW",
    mark: "soft",
  },
  {
    id: "biz_quickfix",
    slug: "quickfix-mobiles",
    name: "QuickFix Mobiles",
    categoryId: "repairs",
    categoryLabel: "Repairs",
    description: "Cracked glass, dying batteries, and stubborn charging ports.",
    tags: ["Screens", "Batteries"],
    rating: 4.2,
    reviewCount: 210,
    location: { lat: 12.9368, lng: 77.6279 },
    neighborhood: "Koramangala 7th Block",
    address: "105, 7th Main, Koramangala, Bengaluru",
    hours: week("10:00", "21:30"),
    typicalResponseMinutes: 10,
    monogram: "QF",
    mark: "line",
  },
  {
    id: "biz_key_latch",
    slug: "key-and-latch",
    name: "Key & Latch",
    categoryId: "more",
    categoryLabel: "Keys & locks",
    description:
      "Keys cut while you wait. Duplicate house keys, lock work, and a tray of spare fobs.",
    tags: ["Key cutting", "Locks"],
    rating: 4.7,
    reviewCount: 64,
    location: { lat: 12.9314, lng: 77.6252 },
    neighborhood: "Koramangala 5th Block",
    address: "2, 5th Main, Koramangala, Bengaluru",
    hours: week("09:30", "20:00", [0]),
    typicalResponseMinutes: 15,
    monogram: "KL",
    mark: "soft",
  },
];

export function getBusinessBySlug(slug: string): Business | undefined {
  return BUSINESSES.find((business) => business.slug === slug);
}

export function getBusinessById(id: string): Business | undefined {
  return BUSINESSES.find((business) => business.id === id);
}
